### ISSUE TITLE
User ending up on old Github from Beta website

### ISSUE THREAD

**Issue by dashouse** [alphagov/govuk-prototype-kit-private-beta#46]
When a user navigates from the Design System to the Beta prototype kit and clicks on either GitHub link they are directed to the old version of the kit.

This is confusing for users that understand there is a new kit, I imagine even more confusing for someone that doesn't and tries to use the new stuff.

https://www.dropbox.com/s/pppf3euvjhjf6zy/nimbus-record-video-2018-05-22-13-41-25.webm?dl=0

**Comment by joelanman** [comment]
fixed by #47
