### ISSUE TITLE
Frontend JavaScript is not running in /docs

### ISSUE THREAD

**Issue by joelanman** [alphagov/govuk-prototype-kit-private-beta#51]
The JavaScript in GOV.UK Frontend (for example for button link shim) is not being included or run in the Prototype Kit.

UPDATE

This only affects /docs (the documentation site)

**Comment by igloosi** [comment]
Trello ticket: https://trello.com/c/S84vYp0J/1029-frontend-javascript-is-not-being-included-or-initialised-in-the-prototype-kit
