### ISSUE TITLE
serviceName seems to have stopped working

### ISSUE THREAD

**Issue by joelanman** [alphagov/govuk-prototype-kit-private-beta#57]
reproduce:

Set a serviceName in `app/config.js`

Expected the service name to change in the header, but it doesn't.

UPDATE

It's this line:

https://github.com/alphagov/govuk-prototype-kit-private-beta/blob/master/server.js#L211

I think we might need [Object.assign](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign) to make a separate copy of `app.locals`, as it is one affects the other.

**Comment by igloosi** [comment]
me broke it :( 
Fixed in the PR
